# Generated by Django 6.0.3 on 2026-09-19 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisor', '0003_advisorprofile_consultation_rate'),
        ('question', '0002_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('NPR', 'Nepali Rupee')], default='NPR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('khalti_txn_id', models.CharField(blank=True, help_text='Khalti transaction ID', max_length=100, null=True)),
                ('khalti_idx', models.CharField(blank=True, help_text='Khalti payment index', max_length=100, null=True)),
                ('payment_method', models.CharField(default='khalti', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='advisor.advisorprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='question.question')),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
