# Generated by Django 5.2.12 on 2026-04-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique='True')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveBigIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
