# Generated by Django 6.0.3 on 2026-09-19 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionerprofile',
            name='areas_of_interest',
            field=models.TextField(blank=True, help_text="Comma-separated list of areas you're interested in"),
        ),
        migrations.AddField(
            model_name='questionerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionerprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='questionerprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='questionerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questionerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
