# Generated by Django 5.2.12 on 2026-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_id', models.ImageField(upload_to='advisor_verification/government_ids/')),
                ('certificate', models.FileField(upload_to='advisor_verification/certificates/')),
                ('professional_license', models.FileField(blank=True, null=True, upload_to='advisor_verification/licenses/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
