# Generated by Django 6.0.3 on 2026-09-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='consultation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation rate per session in NPR', max_digits=10),
        ),
    ]
