# Generated by Django 5.2.12 on 2026-06-29 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisor', '0001_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorprofile',
            name='expertise',
            field=models.ManyToManyField(related_name='advisors', to='question.category'),
        ),
        migrations.AddField(
            model_name='advisorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisorverification',
            name='advisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='advisor.advisorprofile'),
        ),
    ]
