# Generated by Django 6.0.3 on 2026-09-18 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('question_accepted', 'Question Accepted'), ('answer_submitted', 'Answer Submitted'), ('review_received', 'Review Received'), ('new_question', 'New Question'), ('payment_received', 'Payment Received'), ('system', 'System Notification')], default='system', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_question_id', models.IntegerField(blank=True, help_text='ID of related question if applicable', null=True)),
                ('related_advisor_id', models.IntegerField(blank=True, help_text='ID of related advisor if applicable', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
